name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy
        run: |
          # Replace with your build commands if needed (e.g., npm run build)
          echo "Build your static content here"
          # Deploy to GitHub Pages
          echo "Deploying to GitHub Pages"
          # Remove existing index.html if it exists
          rm -f index.html
          # Create a simple redirect index.html
          echo "<html><head><meta http-equiv='refresh' content='0; URL=/Bank-Application/bank_app/src/main/webapp/index.jsp'></head><body></body></html>" > index.html
          # Commit and push changes to GitHub Pages branch
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add index.html
          git commit -m "Deploy redirect to index.jsp"
          git push

